### ISSUE TITLE
Everwing extension caused display flickering?

### ISSUE THREAD

**Issue by Dzampano13** [0x4754/Everwing-Hacks-Reloaded-Extension#1]
I tried to install everwing extension on Opera browser in Linux Mint. I dropped .crx file in opera but nothing happened. After that my display started flickering. Then I installed extension in Windows 8.1. Extension was successfully added to browser, but didn't work and again, after that my display started flickering and never stopped. I tried many fixes but non of them could resolve the problem. Eventually I had to remove Video card from motherboard. Now my display works on Intel HD Graphics and does not flicker.  I have never had flickering problems before neither in Linux nor in Windows. Could it have been caused by Everwing extension?

**Comment by 0x4754** [comment]
I have experienced GPU problems with Opera in the past, on both linux and windows, but this is not an extension problem. The extension may produce more load than the GPU or your drivers can handle which triggers the problem.

In my case, disabling the browser's hardware acceleration always fixes any browser display related problem.

I haven't tested if the extension works since the last update. Normally, after you open the game, you click the extension icon on the bar and apply a cheat (it should say synced on the top status info).
